### ISSUE TITLE
I can't see the content when offline

### ISSUE THREAD

**Issue by aruprakshit** [divyansh7924/workbox-example-with-cra#1]
I am following your github repo to check how you did it. I cloned it, then when I take the app offline, I don;t see the "hello world" as I see it when I am online. How do I test it if it is working or not? Would you help?

**Comment by akana** [comment]
I met the same problem. I found that the static files have not been precaching. I solved the problem by caching all the files.

sw-build.js

...
globPatterns: ['**/*.{jpg}'],
....


update `globPatterns` as below
...
globPatterns: ["**/*.{js,css,html,png,jpg,svg}"]
....

Hope it can help you

**Comment by divyansh7924** [comment]
Yes that will solve it.
